"""Every v2 constant with its reason. tests/engine_v2/test_config_ledger.py fails on a constant missing here
or a value that differs from the code."""

SPEC = "textbook definition fixed in engine_v2/specs before any replay (2026-09-16)"

LEDGER = {
    # market model
    "market_model.structure.SWING_ATR": (1.0, "zigzag reversal of 1 ATR on the swing timeframe; ATR-scaled, no pip floors", SPEC),
    "market_model.zones.FVG_MIN_ATR": (0.10, "an imbalance smaller than 0.1 ATR is quote noise", SPEC),
    "market_model.zones.DISPLACEMENT_ATR": (1.2, "a displacement bar is at least 1.2 ATR", SPEC),
    "market_model.zones.DISPLACEMENT_BODY": (0.6, "a displacement bar is mostly body", SPEC),
    "market_model.zones.BASE_MAX_ATR": (1.2, "a base is a tight consolidation", SPEC),
    "market_model.zones.BASE_BODY_MAX": (0.5, "base candles have small bodies", SPEC),
    "market_model.zones.DEPARTURE_ATR": (1.5, "strong departure from the base", SPEC),
    "market_model.zones.DEPARTURE_WITHIN": (3, "departure within three bars of the base", SPEC),
    "market_model.volume.VALUE_AREA": (0.70, "standard 70% value area", SPEC),
    "market_model.volume.BIN_ATR": (0.02, "profile bin = 2% of daily ATR", SPEC),
    "market_model.liquidity.EQUAL_ATR": (0.10, "equal highs/lows within 0.1 ATR", SPEC),
    "market_model.liquidity.EQUAL_SEARCH_BARS": (480, "an equal-high/low pool stays live five days", SPEC),
    # common
    "categories._common.STOP_BUFFER_ATR": (0.10, "stop buffer beyond invalidation", SPEC),
    "categories._common.STOP_BUFFER_SPREAD": (1.5, "stop buffer at least 1.5 spreads", SPEC),
    # SMC
    "categories.smc.SMC_BOS_WINDOW": (8, "displacement must break structure within 8 M15 bars of the sweep", SPEC),
    "categories.smc.SMC_ENTRY_BARS": (12, "retrace into the FVG within 3 hours", SPEC),
    "categories.smc.TIME_STOP_BARS": (96, "24h time stop", SPEC),
    "categories.smc.T2_MAX_R": (6.0, "opposing pool must be within 6R", SPEC),
    "categories.smc.T2_FALLBACK_R": (3.0, "T2 when no pool is in reach", SPEC),
    # STRUCTURE
    "categories.structure.STRUCT_VALID_H1": (120, "a fresh zone rests five days", SPEC),
    "categories.structure.TIME_STOP_H1": (72, "three-day time stop", SPEC),
    "categories.structure.CONFIRM_VALID_M15": (4, "confirmation entry valid one hour", SPEC),
    "categories.structure.SR_TOL_ATR": (0.25, "S/R confluence tolerance", SPEC),
    # TREND
    "categories.trend.IMPULSE_MIN_ATR": (2.0, "an impulse is at least 2 H1 ATR", SPEC),
    "categories.trend.ENTRY_VALID_M15": (4, "stop entry valid one hour", SPEC),
    "categories.trend.TIME_STOP_M15": (96, "24h time stop", SPEC),
    "categories.trend.STOP_BUFFER_H1_ATR": (0.10, "stop buffer beyond the pullback extreme", SPEC),
    # ORDER_FLOW
    "categories.order_flow.OF_BACK_INSIDE": (2, "two closes back inside value = failed auction", SPEC),
    "categories.order_flow.OF_ACCEPT": (3, "three closes outside value = acceptance", SPEC),
    "categories.order_flow.ACCEPT_VALID_BARS": (8, "retest of the value edge within two hours", SPEC),
    "categories.order_flow.TIME_STOP_BARS": (48, "12h time stop", SPEC),
    "categories.order_flow.DAY_START_SECONDS": (3600, "the day's auction starts after rollover", SPEC),
    # MOMENTUM
    "categories.momentum.MOM_SQUEEZE_BARS": (6, "a squeeze lasts at least six M15 bars", SPEC),
    "categories.momentum.ENTRY_VALID_BARS": (3, "release entry valid 45 minutes", SPEC),
    "categories.momentum.TIME_STOP_BARS": (48, "12h time stop", SPEC),
    "categories.momentum.MAX_STOP_ATR": (3.0, "switch to the squeeze midpoint beyond 3 ATR", SPEC),
    # MEAN_REVERSION
    "categories.mean_reversion.MR_ER_MAX": (0.30, "balance regime: H1 efficiency ratio below 0.3", SPEC),
    "categories.mean_reversion.MR_SIGMA": (2.0, "stretch of two sigma from VWAP", SPEC),
    "categories.mean_reversion.SIGMA_BARS": (96, "sigma over one day of M15", SPEC),
    "categories.mean_reversion.RSI_EXTREME": (25.0, "RSI extreme", SPEC),
    "categories.mean_reversion.RSI_BACK": (30.0, "RSI back inside", SPEC),
    "categories.mean_reversion.LOOKBACK": (4, "stretch and extreme within the last hour", SPEC),
    "categories.mean_reversion.STOP_BARS": (8, "stop beyond the last two hours' extreme", SPEC),
    "categories.mean_reversion.STOP_BUFFER_ATR": (0.20, "reversion stop buffer", SPEC),
    "categories.mean_reversion.MR_TIME_BARS": (16, "reversion must work within four hours", SPEC),
    # WAVE
    "categories.wave.WY_RANGE_BARS": (30, "trading range over 30 H1 bars", SPEC),
    "categories.wave.WY_MAX_HEIGHT_ATR": (4.0, "a range is at most 4 ATR tall", SPEC),
    "categories.wave.WY_TOUCH_ATR": (0.25, "touch tolerance of the range edges", SPEC),
    "categories.wave.WY_SPRING_ATR": (0.10, "spring/upthrust beyond the edge by 0.1 ATR", SPEC),
    "categories.wave.WY_TEST_BARS": (10, "test within ten bars", SPEC),
    "categories.wave.WY_TEST_BAND_ATR": (0.5, "test near the range edge", SPEC),
    "categories.wave.DB_EQUAL_ATR": (0.30, "double bottom/top tolerance", SPEC),
    "categories.wave.DB_MIN_BARS": (5, "pattern at least five bars wide", SPEC),
    "categories.wave.DB_MAX_BARS": (60, "pattern at most sixty bars wide", SPEC),
    "categories.wave.DB_NECK_ATR": (1.5, "neckline at least 1.5 ATR from the bottoms", SPEC),
    "categories.wave.DB_MAX_STOP_ATR": (4.0, "switch to the half-pattern stop beyond 4 ATR", SPEC),
    "categories.wave.EW_W1_ATR": (3.0, "wave 1 at least 3 ATR", SPEC),
    "categories.wave.H1_ENTRY_VALID": (3, "H1 stop entry valid three bars", SPEC),
    "categories.wave.TIME_STOP_H1": (72, "three-day time stop", SPEC),
    # CROSS_ASSET
    "categories.cross_asset.CA_SIGMA": (2.5, "divergence of 2.5 sigma from the implied rate", SPEC),
    "categories.cross_asset.CA_PERSIST": (3, "divergence must persist three M15 closes (v1 one-minute fades lost)", SPEC),
    "categories.cross_asset.SIGMA_BARS": (96, "sigma over one day of M15", SPEC),
    "categories.cross_asset.STOP_BUFFER_ATR": (0.20, "stop buffer beyond the 3-bar extreme", SPEC),
    "categories.cross_asset.TIME_STOP_BARS": (16, "convergence must happen within four hours", SPEC),
    # v2.1 rules (engine_v2/run/forensics.py; reports/v2/RULE_FINDINGS.md). Cut points = discovery tertiles 2010-2020.
    "categories.smc.ROOM_MIN_R": (0.5, "next opposing D1 level at least 0.5R beyond entry", "forensics 2026-09-16: 53%/+0.28R -> 69%/+0.63R with no weekly pools"),
    "categories.structure.VOL_PCT_LOW": (0.25, "v3.0: medium volatility regime, lower edge", "crosspair 2026-09-17: chosen in 5/5 folds; held-out 553 trades 68.4%/+0.096R t=2.19"),
    "categories.structure.VOL_PCT_HIGH": (0.68, "v3.0: medium volatility regime, upper edge", "crosspair 2026-09-17: fold cut points 0.653-0.701"),
    "categories.structure.PARTIAL_AT_R": (0.5, "v3.0: half off at +0.5R then breakeven", "crosspair 2026-09-17: 'half' exit family passed, 'std' did not"),
    "categories.trend.VOL_PCT_MAX": (0.33, "pullbacks only when ATR is in its lowest third", "forensics 2026-09-16: 52%/+0.06R -> 53%/+0.04R"),
    "categories.momentum.ROOM_MIN_R": (0.38, "release needs room to the next opposing D1 level", "forensics 2026-09-16: with no NY 60%/+0.18R -> 54%/+0.12R"),
    "categories.wave.WY_ENABLED": (False, "Wyckoff definition lost in both periods; off until rebuilt", "forensics 2026-09-16: 34%/-0.25R -> 34%/-0.34R"),
    "categories.wave.NO_FRIDAY": (True, "Friday pattern entries lose in both periods", "forensics 2026-09-16: -0.08R -> -0.07R"),
    "market_model.location.ROOM_CAP_R": (10.0, "room beyond 10R counts as open space", SPEC),
    "market_model.location.RANGE_DAYS": (20, "one trading month of D1 range", SPEC),
    "market_model.location.VOL_LOOKBACK": (250, "about one year of bars for the volatility percentile", SPEC),
    "categories.smc.PARTIAL_AT_R": (0.5, "v3: half off at +0.5R then breakeven", "exit lab 2026-09-17: 66%/+0.04R -> 74%/+0.31R"),
    "categories.trend.PARTIAL_AT_R": (0.5, "v3: half off at +0.5R then breakeven", "exit lab 2026-09-17: 67%/+0.04R -> 68%/+0.06R"),
    "categories.momentum.PARTIAL_AT_R": (0.5, "v3: half off at +0.5R then breakeven", "exit lab 2026-09-17: 74%/+0.15R -> 73%/+0.11R"),
    # D1 trend following (high-expectancy lab, textbook Donchian specs, no tuning)
    "categories.trend_d1.BREAKOUT_DAYS": (55, "classic 55-day breakout", SPEC),
    "categories.trend_d1.STOP_ATR": (2.0, "initial stop 2 x ATR(20)", SPEC),
    "categories.trend_d1.ATR_DAYS": (20, "ATR(20) on D1", SPEC),
    "categories.trend_d1.FAR_TARGET_R": (100.0, "runner: no fixed target", SPEC),
    "categories.trend_d1.TIME_STOP_D1": (500, "two-year safety time stop", SPEC),
    # probability, risk, execution
    "probability.frequency.Z95": (1.959964, "two-sided 95% normal quantile for the Wilson range", "statistics"),
    "probability.frequency.MIN_SAMPLE": (100, "below 100 trades a win frequency is too uncertain to call a probability", SPEC),
    "risk.MAX_RISK_PER_TRADE": (0.02, "operator rule: 2% of the budget ($4 of $200)", "operator, 2026-09-15"),
    "risk.MAX_RISK_OVERSHOOT": (1.10, "a minimum lot may risk at most 10% over the asked risk", "v1 core/market_stop.py"),
    "execution.orders.V2_MAGIC": (2002, "separates v2 positions from v1 (1001)", SPEC),
    "execution.orders.DEVIATION_POINTS": (20, "same deviation as v1 market orders", "v1 core/execution.py"),
    "execution.orders.V2_LIVE_ORDERS": (False, "no live orders until the operator enables v2", "roadmap phase 11"),
    "journal.journal.V2_JOURNAL_MONGO": (False, "JSONL journal until MongoDB wiring is approved", SPEC),
    "sim.outcome.MAX_HOLD_SECONDS": (864000, "safety cap when a spec has no time stop", SPEC),
}
